server:
  port: 8087


feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

#必须，无需更改
logging:
  config: classpath:log4j2.xml


#必须，无需更改
eventlog:
  component: 设计家平台
  subSystem: ${spring.application.name}
  framework: J2EE+SpringCloud

spring:
  application:
    name: quote-system-app
  http:
    encoding:
      charset: UTF-8
      force: true
      forceRequest: true
      forceResponse: true
  jersey:
    enabled: true
    urlMappings: /api/*
    jaxrsApplicationClass: com.juran.quote.config.RestJerseyRegister
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 5000

mongodb:
  base:
    enabled: true
    hostPort: 47.94.207.68:30008
    userName: pUser
    passWord: pUser
    database: quote
    connectTimeout: 8000  #连接超时
    socketTimeout: 8000   #执行时间超时
    serverSelectionTimeout: 8000   #等待应用程序超时
    accessEnvironment: local  #local:将会采用url方式连接,server:将会采用上面的方式连接
    #    url: mongodb://pUser:pUser@dds-2ze69b666695b6642423-pub.mongodb.rds.aliyuncs.com:3717/quote?socketTimeout=8000&connectTimeout=8000&serverSelectionTimeout=8000
    url: mongodb://pUser:pUser@dds-2ze909f9667243741883-pub.mongodb.rds.aliyuncs.com:3717/quote?socketTimeout=8000&connectTimeout=8000&serverSelectionTimeout=8000

springfox:
  config:
    enabled: true
    configId: pkg-swagger2-jersey2
    title:  报价系统服务接口列表
    version:  1.0.0
    contact: 暂无联系人
    schemes: http,https
    basePath: /api
    resourcePackage: com.juran.quote
    prettyPrint: true
    scan: true
  documentation:
    swagger:
      v2:
        path: /api/swagger.json #/v2/api-docs


id.generator:
  enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://alp-hb2-a-emall-external.mysql.rds.aliyuncs.com:3306/id_generator?useUnicode=true&characterEncoding=utf-8
    username: sjjdev
    password: CqJcZ*4@5%8#Mg
    maxActive: 10
    initialSize: 1

#keyManager配置
keyManagerConfig:
  sendUrl: http://47.94.207.68:30049

#报价配置
quote:
  budgetAreaMax: 1000
  defaultNewPackageId: 300009
  defaultOldPackageId: 300025
  tokenName: sjj_token_alpha
  user: user_alpha
  shareUrl: https://alpha-www.homestyler.com/cn/share/quoteShare/{0}
  quoteResultUrl: https://alpha-www.homestyler.com/cn/quoteResult/{0}

#3D路径配置
thirdUrl:
  miniProductUrl: https://fpmw.homestyler.com/api/rest/v1.0/miniproducts/search
  miniProductType: sort=rank&order=desc&tenant=ezhome&l=zh_CN&branch=&status=1&treeId=front-category-root&categoriesIds=73db312e-1067-4a70-a49a-3a8bf69adbcf&attributeIds=55d5456e-a5d9-4725-970d-1404f8a8f6ab_7f537d66-58de-11e8-9c2d-fa7ae01bbebc
  allCategoryUrl: http://123.56.5.77:30014/category/api/v1/getCateories
  getDecorationCompanyUrl: http://47.94.166.213:8808/designapi/Api/getItemInfo?caseId=
#  allCategoryUrl: http://tbmw.3d.svc.cluster.localcategory/api/v1/getCateories

threadPool:
  corePoolSize: 20
  maxPoolSize: 50
  queueCapacity: 200
  keepAliveSeconds: 60
  threadNamePrefix: quoteTaskExcutor-
  waitTaskCompleteOnShutdown: true

#配置 redis相关配置
redis:
  enable: true          #激活redis 分布式锁默认激活
  lockFailureTime: 30   #锁失效时间  单位：s
  spinNum: 20           #自旋次数
  spinThreadTime: 500   #自旋等待时间 单位：ms